jobs:
  - name: globox_build_x11_software
    plan:
      - task: globox_build_x11_software_lib
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_x11_gcc
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_x11_gcc
          run:
            path: /scripts/build_x11.sh
            args: ["release", "x11", "software", "none", "native"]
      - task: globox_build_x11_software_simple_example
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_x11_gcc
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_x11_gcc
          run:
            path: /scripts/build_x11.sh
            args: ["release", "x11", "software", "simple", "native"]
      - task: globox_build_x11_software_complex_example
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_x11_gcc
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_x11_gcc
          run:
            path: /scripts/build_x11.sh
            args: ["release", "x11", "software", "complex", "native"]
  - name: globox_build_x11_vulkan
    plan:
      - task: globox_build_x11_vulkan_lib
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_x11_gcc
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_x11_gcc
          run:
            path: /scripts/build_x11.sh
            args: ["release", "x11", "vulkan", "none", "native"]
      - task: globox_build_x11_vulkan_simple_example
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_x11_gcc
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_x11_gcc
          run:
            path: /scripts/build_x11.sh
            args: ["release", "x11", "vulkan", "simple", "native"]
      - task: globox_build_x11_vulkan_complex_example
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_x11_gcc
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_x11_gcc
          run:
            path: /scripts/build_x11.sh
            args: ["release", "x11", "vulkan", "complex", "native"]
  - name: globox_build_x11_egl
    plan:
      - task: globox_build_x11_egl_lib
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_x11_gcc
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_x11_gcc
          run:
            path: /scripts/build_x11.sh
            args: ["release", "x11", "egl", "none", "native"]
      - task: globox_build_x11_egl_simple_example
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_x11_gcc
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_x11_gcc
          run:
            path: /scripts/build_x11.sh
            args: ["release", "x11", "egl", "simple", "native"]
      - task: globox_build_x11_egl_complex_example
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_x11_gcc
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_x11_gcc
          run:
            path: /scripts/build_x11.sh
            args: ["release", "x11", "egl", "complex", "native"]
  - name: globox_build_appkit_osxcross_software
    plan:
      - task: globox_build_appkit_software_lib
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_appkit_osxcross
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_appkit_osxcross
          run:
            path: /scripts/build_appkit.sh
            args: ["release", "appkit", "software", "none", "osxcross"]
      - task: globox_build_appkit_software_simple_example
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_appkit_osxcross
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_appkit_osxcross
          run:
            path: /scripts/build_appkit.sh
            args: ["release", "appkit", "software", "simple", "osxcross"]
      - task: globox_build_appkit_software_complex_example
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_appkit_osxcross
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_appkit_osxcross
          run:
            path: /scripts/build_appkit.sh
            args: ["release", "appkit", "software", "complex", "osxcross"]
  - name: globox_build_appkit_osxcross_vulkan
    plan:
      - task: globox_build_appkit_vulkan_lib
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_appkit_osxcross
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_appkit_osxcross
          run:
            path: /scripts/build_appkit.sh
            args: ["release", "appkit", "vulkan", "none", "osxcross"]
      - task: globox_build_appkit_vulkan_simple_example
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_appkit_osxcross
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_appkit_osxcross
          run:
            path: /scripts/build_appkit.sh
            args: ["release", "appkit", "vulkan", "simple", "osxcross"]
      - task: globox_build_appkit_vulkan_complex_example
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_appkit_osxcross
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_appkit_osxcross
          run:
            path: /scripts/build_appkit.sh
            args: ["release", "appkit", "vulkan", "complex", "osxcross"]
  - name: globox_build_appkit_osxcross_egl
    plan:
      - task: globox_build_appkit_egl_lib
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_appkit_osxcross
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_appkit_osxcross
          run:
            path: /scripts/build_appkit.sh
            args: ["release", "appkit", "egl", "none", "osxcross"]
      - task: globox_build_appkit_egl_simple_example
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_appkit_osxcross
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_appkit_osxcross
          run:
            path: /scripts/build_appkit.sh
            args: ["release", "appkit", "egl", "simple", "osxcross"]
      - task: globox_build_appkit_egl_complex_example
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_appkit_osxcross
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_appkit_osxcross
          run:
            path: /scripts/build_appkit.sh
            args: ["release", "appkit", "egl", "complex", "osxcross"]
  - name: globox_build_win_software
    plan:
      - task: globox_build_win_software_lib
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_win_mingw
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_win_mingw
          run:
            path: /scripts/build_win.sh
            args: ["release", "win", "software", "none", "native"]
      - task: globox_build_win_software_simple_example
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_win_mingw
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_win_mingw
          run:
            path: /scripts/build_win.sh
            args: ["release", "win", "software", "simple", "native"]
      - task: globox_build_win_software_complex_example
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_win_mingw
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_win_mingw
          run:
            path: /scripts/build_win.sh
            args: ["release", "win", "software", "complex", "native"]
  - name: globox_build_win_wgl
    plan:
      - task: globox_build_win_wgl_lib
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_win_mingw
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_win_mingw
          run:
            path: /scripts/build_win.sh
            args: ["release", "win", "wgl", "none", "native"]
      - task: globox_build_win_wgl_simple_example
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_win_mingw
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_win_mingw
          run:
            path: /scripts/build_win.sh
            args: ["release", "win", "wgl", "simple", "native"]
      - task: globox_build_win_wgl_complex_example
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_win_mingw
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_win_mingw
          run:
            path: /scripts/build_win.sh
            args: ["release", "win", "wgl", "complex", "native"]
  - name: globox_build_appkit_native
    plan:
      - task: globox_build_appkit_software_task
        config:
          platform: darwin
          run:
            path: /bin/bash
            args: ["--login", "/Users/nullgemm/Documents/concourse/bin/globox_scripts_appkit_native/build_software.sh"]
      - task: globox_build_appkit_egl_task
        config:
          platform: darwin
          run:
            path: /bin/bash
            args: ["--login", "/Users/nullgemm/Documents/concourse/bin/globox_scripts_appkit_native/build_egl.sh"]
      - task: globox_build_appkit_vulkan_task
        config:
          platform: darwin
          run:
            path: /bin/bash
            args: ["--login", "/Users/nullgemm/Documents/concourse/bin/globox_scripts_appkit_native/build_vulkan.sh"]
