jobs:
  - name: globox_build_x11
    plan:
      - task: globox_build_x11_task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/globox_image_x11_gcc
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: globox_image_x11_gcc
          run:
            path: /scripts/build_x11.sh
